# ##### SUCCESS #####

# ##### ERROR #####
CODE_ERROR_INTERNAL_LIBRARY = "ERROR_INTERNAL_LIBRARY"
CODE_ERROR_GENERIC = "ERROR_GENERIC"

# ##### NOT #####

# ##### NOT_VALID #####
CODE_NOT_VALID_INTEGER = "NOT_VALID_INTEGER"

# ##### NOT_EXISTS #####

# ##### ALREADY_EXISTS #####

# ##### NOT_FOUND #####
CODE_NOT_FOUND_TEMPLATE = "NOT_FOUND_TEMPLATE"
